version: '3.8'

services:
  exporter-to-obsidian:
    image: geselle/exporter-to-obsidian:latest
    container_name: exporter-to-obsidian
    volumes:
      - /Users/joy/Documents/SecondBrain:/output
    env_file:
      - .env.production
    restart: unless-stopped

# 使用说明：
# 1. 准备 .env.production 文件，包含必要的环境变量
# 2. 运行: docker-compose up -d
# 3. 输出文件将保存在 ./output 目录中